### ISSUE TITLE
Calling @leycec

### ISSUE THREAD

**Issue by fredrikaverpil** [fredrikaverpil/pyside2-linux#1]
@leycec hey,

If you have the time, I would be interested to hear if any of these work for you:
https://github.com/fredrikaverpil/pyside2-linux/releases/tag/2018.01.25

Details: https://travis-ci.org/fredrikaverpil/pyside2-linux/builds/333293532

:beers: 😄

**Comment by leycec** [comment]
Phenomenal work as ever. Ironically, we're now on the cusp of capitulating to best practices in the Python community and embracing [(Ana|Mini)conda](https://anaconda.org) for the entirety of our install path.

We've pretty much "had it" with cross-platform `pip`, `setuptools`, and `wheel` incompatibilities. At this point, we just need a packaging solution that works out-of-the-box on all major platforms. Increasingly, that means [conda-forge](https://conda-forge.org) rather than PyPI – which probably means hosting at least two conda-forge packages of our own, each depending upon the existing [PySide2 conda-forge recipe](https://github.com/conda-forge/pyside2-feedstock).

I'd love to be talked out of this. Unfortunately, the difficulty of installing optimized (i.e., parallelized) versions of prominent scientific Python packages like `matplotlib`, `numpy`, and `scipy` with the standard Python packaging ecosystem all but makes [(Ana|Mini)conda](https://anaconda.org) a necessity.

Also, [**this**](https://bugreports.qt.io/browse/PYSIDE-588) may be of interest. I was initially enraged, of course, but your mileage may vary. I now feel only a deep, abiding regret at having adopted PySide2 early. In hindsight, I should have bit the GPL-encumbered bullet and embraced PyQt5, the obvious industry standard. Thanks to the psychology of previous investment, however, our GUI is too deeply entwined with PySide2 to reasonably turn this derailing train around now. `</sigh>`

*Anyway.* It's my birthday today. I'm feeling kinda depressed about the lackluster state of our PySide2-based project, which is sufficiently late over deadline that it's now in imminent danger of being dropped  –  and me with it. So, take everything above with a generous grain of salt. Such is life, right?

Thanks again for all the intrepid work, Fred. You remain awesome. If by some tenuous miracle we *do* embrace a wheel-oriented solution, your newest collection of wheels is at the head of our interest list.

**Comment by fredrikaverpil** [comment]
Hi @leycec !

Feels like we should perhaps continue this conversation in a less exposed fashion, so in case you wish to do that; `fredrik@averpil.com`.

> we're now on the cusp of capitulating to best practices in the Python community and embracing (Ana|Mini)conda for the entirety of our install path.

Sounds good. I actually use (mini)conda for all of my envs management and we install PySide2 this way currently at work too, since it just works so well on all platforms.

> we just need a packaging solution that works out-of-the-box on all major platforms

I agree, and I really think conda with conda-forge is the only option. It troubles me a little bit that this is a commercial solution and not a truly open source one though – but perhaps that detail is what's going to make it work long-time too. I'm not going to try to talk you out of it. Not trying to talk myself out of it either.

> Also, this may be of interest.

I think QtC views PySide2 as something widely unreleased... I mean they don't even maintain a version string, which is odd to me personally, as I would maintain a version string of anything I do and make publicly available.

Since the state of cross-platform Python UIs on desktops is in such an ugly state, I think PySide2 took off much faster than they had anticipated.

A name change wouldn't surprise me that much... but yeah, the sheer amount of hours they'll probably have to invest... yeah.

> regret at having adopted PySide2 early

Is it too late to switch over to PyQt5?
It's a long shot, but perhaps this could help switching: https://github.com/mottosso/Qt.py

> Anyway. It's my birthday today. I'm feeling kinda depressed about the lackluster state of our PySide2-based project, which is sufficiently late that it's now in imminent danger of being dropped – and me with it. So, take everything above with a generous grain of salt. Such is life, eh?

First; oh, happy birthday!! 🍰 🎈🎉   Secondly; I'm very sad to hear about your situation. I really hope that you'll be able to turn things around and not get you or your project dropped.

**Disclaimer:** these wheels are still just an experiment and a short-term solution for me to quickly have working wheels at hand when I need them for R&D. I didn't mean for you to commit or invest any time into this. In case you happen to want to try them out, just let me know if you had any issues or not.
